fieldLayouts:
  394a5ca3-9f9c-48e7-9e49-b271809bcfc3:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: fdc2e766-f2a8-4ee0-9ad8-9b7d64b8d86b # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 05fb56bd-4689-45e9-9445-a535cfa2460c # Limit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 1
handle: dynamic
hasTitleField: true
name: Dynamic
section: 149763f1-bd8b-4d8e-a8f0-8ce1b0c6d593 # Featured Plugins
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
