defaultPlacement: end
fieldLayouts:
  1a87d433-2ba9-4da1-b279-2fd70eb3fbfc:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: dd2601c5-8443-448c-980a-c9a1ee040ee9 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fdc2e766-f2a8-4ee0-9ad8-9b7d64b8d86b # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: pluginCategories
name: 'Plugin Categories'
siteSettings:
  2a835d29-b3e4-4ef5-bf62-ad7285b4a4dd: # API
    hasUrls: false
    template: null
    uriFormat: null
  2f57d7c9-711e-4173-a5b4-df89fb34e085: # Craft Plugin Store
    hasUrls: false
    template: null
    uriFormat: null
  8928c23a-7002-467d-af97-333694b8dad8: # Craft ID
    hasUrls: false
    template: null
    uriFormat: null
  b9fcbb50-cec0-46a4-a28f-4c93be8e0c95: # Feeds
    hasUrls: false
    template: null
    uriFormat: null
  dfc27822-23dd-49e2-ac3a-66a436674cf0: # Composer
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 421bb5e6-a177-40c3-8d22-6e133ee070a4
