columnSuffix: null
contentColumnType: boolean
fieldGroup: 4987fb8d-cf45-4b60-a94f-51c591336558 # License
handle: autoRenew
instructions: ''
name: 'Auto Renew'
searchable: true
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
