columnSuffix: null
contentColumnType: text
fieldGroup: add7f1c8-5c4a-4d23-9398-8a9472f169e8 # User
handle: businessAddressLine1
instructions: ''
name: 'Business Address Line 1'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
