columnSuffix: null
contentColumnType: text
fieldGroup: b1a59dd4-5d0c-4d32-925c-8a2349747691 # Order
handle: cardToken
instructions: ''
name: 'Card Token'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
