columnSuffix: null
contentColumnType: text
fieldGroup: 4987fb8d-cf45-4b60-a94f-51c591336558 # License
handle: domain
instructions: ''
name: Domain
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
