columnSuffix: null
contentColumnType: 'decimal(12,2)'
fieldGroup: ec01a46c-7aae-4b10-95ce-6ae6648b9745 # Plugin
handle: updatePrice
instructions: ''
name: 'Update Price'
searchable: true
settings:
  decimals: '2'
  defaultValue: null
  max: null
  min: null
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
